general {
  colors = true
  interval = 30
}

order += "volume master"
order += "ipv6"
order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
order += "tztime local"
order += "user"

volume master {
  format = "V: %volume"
  device = "default"
  mixer = "Master"
  mixer_idx = 0
}

wireless _first_ {
  format_up = "W: (%quality at %essid) %ip"
  format_down = ""
}

ethernet _first_ {
  format_up = "E: %ip"
  format_down = ""
}

battery all {
  format = "%status %percentage %remaining"
  format_down = ""
}

tztime local {
  format = "%Y-%m-%d %H:%M:%S"
}
